services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=boilerplate
    ports:
      - 5432:5432
