services:
  app:
    build: .
    container_name: boilerplate-golang
    env_file:
      - .env
    environment:
      - DB_HOST=postgres-standalone
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped
    networks:
      - shared-net

networks:
  shared-net:
    external: true
