// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"database/sql"
	"time"
)

type Directory struct {
	Guid          string         `json:"guid"`
	DirectoryGuid sql.NullString `json:"directory_guid"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DeletedBy     sql.NullString `json:"deleted_by"`
}

type File struct {
	Guid          string         `json:"guid"`
	DirectoryGuid string         `json:"directory_guid"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Path          string         `json:"path"`
	Size          int64          `json:"size"`
	Extension     string         `json:"extension"`
	MimeType      string         `json:"mime_type"`
	CreatedAt     time.Time      `json:"created_at"`
	CreatedBy     sql.NullString `json:"created_by"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	UpdatedBy     sql.NullString `json:"updated_by"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	DeletedBy     sql.NullString `json:"deleted_by"`
}

type Permission struct {
	Guid        string         `json:"guid"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

type PermissionRole struct {
	PermissionGuid string `json:"permission_guid"`
	RoleGuid       string `json:"role_guid"`
}

type Role struct {
	Guid        string         `json:"guid"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   sql.NullString `json:"created_by"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

type Session struct {
	Guid                  string       `json:"guid"`
	UserGuid              string       `json:"user_guid"`
	AccessToken           string       `json:"access_token"`
	AccessTokenExpiredAt  time.Time    `json:"access_token_expired_at"`
	RefreshToken          string       `json:"refresh_token"`
	RefreshTokenExpiredAt time.Time    `json:"refresh_token_expired_at"`
	IpAddress             string       `json:"ip_address"`
	UserAgent             string       `json:"user_agent"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             sql.NullTime `json:"updated_at"`
}

type User struct {
	Guid       string         `json:"guid"`
	Name       string         `json:"name"`
	Email      string         `json:"email"`
	Password   string         `json:"password"`
	RoleGuid   string         `json:"role_guid"`
	VerifiedAt sql.NullTime   `json:"verified_at"`
	IsActive   bool           `json:"is_active"`
	ActiveAt   sql.NullTime   `json:"active_at"`
	ActiveBy   sql.NullString `json:"active_by"`
	CreatedAt  time.Time      `json:"created_at"`
	CreatedBy  sql.NullString `json:"created_by"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	DeletedBy  sql.NullString `json:"deleted_by"`
}

type UserTokenValidation struct {
	Guid      string    `json:"guid"`
	Email     string    `json:"email"`
	Type      string    `json:"type"`
	Token     string    `json:"token"`
	ExpiredAt time.Time `json:"expired_at"`
	CreatedAt time.Time `json:"created_at"`
}
